# Generated by Django 6.0.1 on 2026-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
                ('cpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
